### ISSUE TITLE
bug: calling check_relation from gRPC with an undefined model type crashes the server

### ISSUE THREAD

**Issue by kbirger** [aserto-dev/go-edge-ds#37]
In experimenting with my model, I made a mistake and deleted an object type that I invoked in a check_relation call. This caused a panic in the topaz container, crashing it with the following trace. It seems like it should throw a reasonable error back to the caller instead.

```
panic: runtime error: index out of range [0] with length 0

goroutine 119 [running]:
github.com/aserto-dev/go-edge-ds/pkg/ds.ResolveRelation({0x149a9c0, 0xc00018cea0}, 0x38?, {0xc000320090, 0x8}, {0xc000320080, 0x6})
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-edge-ds@v0.21.7/pkg/ds/model.go:76 +0x507
github.com/aserto-dev/go-edge-ds/pkg/ds.(*checkRelation).newChecker(0xc0005ce080, {0x149a9c0?, 0xc00018cea0}, 0xc00077a000, {0x1ce20a0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-edge-ds@v0.21.7/pkg/ds/check_relation.go:60 +0xc5
github.com/aserto-dev/go-edge-ds/pkg/ds.(*checkRelation).Exec(0xc0005ce080, {0x149a9c0, 0xc00018cea0}, 0xc00077a000?)
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-edge-ds@v0.21.7/pkg/ds/check_relation.go:49 +0x7c
github.com/aserto-dev/go-edge-ds/pkg/directory/v2.(*Reader).CheckRelation.func1(0xc0005d0078?)
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-edge-ds@v0.21.7/pkg/directory/v2/reader.go:437 +0x85
go.etcd.io/bbolt.(*DB).View(0xc0000e3928?, 0xc0000e3930)
        /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:893 +0x82
github.com/aserto-dev/go-edge-ds/pkg/directory/v2.(*Reader).CheckRelation(0xc000454290, {0x149a9c0, 0xc00018cea0}, 0xc00032c910)
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-edge-ds@v0.21.7/pkg/directory/v2/reader.go:435 +0xbb
github.com/aserto-dev/go-directory/aserto/directory/reader/v2._Reader_CheckRelation_Handler.func1({0x149a9c0, 0xc00018cea0}, {0x11916c0?, 0xc00032c910})
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-directory@v0.21.5/aserto/directory/reader/v2/reader_grpc.pb.go:515 +0x78
github.com/aserto-dev/go-edge-ds/pkg/session.(*HeaderMiddleware).Unary.func1({0x149a9c0?, 0xc00018cea0?}, {0x11916c0, 0xc00032c910}, 0xc0003d1a20?, 0xc000128f60)
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-edge-ds@v0.21.7/pkg/session/id.go:30 +0x6c
github.com/aserto-dev/go-directory/aserto/directory/reader/v2._Reader_CheckRelation_Handler({0x11cda00?, 0xc000454290}, {0x149a9c0, 0xc00018cea0}, 0xc0002ce690, 0xc0004541e0)
        /home/runner/go/pkg/mod/github.com/aserto-dev/go-directory@v0.21.5/aserto/directory/reader/v2/reader_grpc.pb.go:517 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00037c960, {0x14a0de0, 0xc000275a00}, 0xc000242900, 0xc000448fc0, 0x1cf6ea0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc00037c960, {0x14a0de0, 0xc000275a00}, 0xc000242900, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:957 +0x18c
```

Seems like the issue is in this method:
https://github.com/aserto-dev/go-edge-ds/blob/main/pkg/ds/model.go#L62

Version: topaz - 0.25.5 gfa8f6ef darwin-amd64 [2023-07-21T23:06:28Z] ()

Please let me know if more information would be helpful. Below is a google drive link to a tgz that I get from `topaz backup -i` in case that's helpful

https://drive.google.com/file/d/1Mks9-dQl0tTDRgZRhHrLLK4ARNdlf28H/view?usp=sharing

**Comment by ronenh** [comment]
If the object type we're filtering on doesn't exist then we're indexing into an empty `relTypeIndex` map: https://github.com/aserto-dev/go-edge-ds/blob/main/pkg/ds/model.go#L76
